global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  health:
    address: ":8080"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

ping:
  entryPoint: health

log:
  level: INFO
  format: json

accessLog:
  format: json
